### ISSUE TITLE
InvalidStateError in Firefox

### ISSUE THREAD

**Issue by coderaiser** [localForage/localForage#70]
In `FF v27.0.1` occurs error:

```
asyncStorage: can't open database: InvalidStateError
InvalidStateError
```

in this code:

``` js
var openreq = indexedDB.open(DBNAME, DBVERSION);
```

In `Chrome v32.0.1700.107 m` everything works fine. 
Could you help me?

**Comment by tofumatt** [comment]
Looks like #448 should fix this one, but if not please let us know and reopen the issue. :smile:

**Comment by karol-f** [comment]
I'm still experiencing 'invalidState' error - [Firefox in 'private mode'](https://www.dropbox.com/s/egknaq8r3bai5or/private_mode_fx.jpg?dl=0)

Do you think @tofumatt that we should reopen this issue?

**Comment by thgreasi** [comment]
@karol-f what version of localforage are you using?
Trying [this codepen](http://codepen.io/thgreasi/pen/ojYKeE) in private mode on Firefox dev edition 48.0a2 fallbacks to the localstorage driver and succesfully retrieves the stored value.

**Comment by karol-f** [comment]
Hi @thgreasi, I'm using latest (1.4.2). Your CodePen is indeed working - [Private mode codepen](https://www.dropbox.com/s/8aihkdufm7hzbfo/private_mode_fx_codepen.png?dl=0) 

I'll check my code for race conditions and misconfigurations (I'm not setting drivers as you in Codepen, I'm not setting them at all).

Thank you for the response!

**Comment by thgreasi** [comment]
This is an example pen and we are only setting the driver preference order to ease experimentation.
Commenting out the `setDriver()` does not affect the result, since this is exactly what localforage does under the hood by default. Keep in mind that setting indexeddb as the only available driver will break the pen on Firefox Private Mode, since as you saw only localstorage is available on that environment.

**Comment by elyobo** [comment]
@thgreasi your pen is exposing an InvalidStateError _and_ also successfully writing and reading via localForage for me with FF 50.1.0+build2-0ubuntu0.16.04.1 in private browsing mode.

![ff](https://cloud.githubusercontent.com/assets/407806/21908285/3ba1005e-d967-11e6-8e94-4124b49defd7.png)

The order of the error is odd though; reading and writing happens fine and then afterwards the error is thrown (which is what I'm seeing in my own application).

**Comment by elyobo** [comment]
I was unable to find a way to catch the error and while FF still seems to work (while generating annoying error messages), private mode in safari was failing completely.

Is there a correct way to catch this error and what's the correct way to detect that _all_ storage engines have failed?

My interim workaround is just to avoid using localForage at all if `window.indexedDB.init('test')` fails; we're just using it as a cache so everything still works, just with more overhead than we would otherwise want.

**Comment by thgreasi** [comment]
> Is there a correct way to catch this error and what's the correct way to detect that all storage engines have failed?

The proper way is to [check the error thrown as shown in this test case](https://github.com/localForage/localForage/blob/4c1b8943cdad64598c6f47eba4b2d1ba526d209b/test/test.nodriver.js#L34-L40). The same error is thrown on all get/set/remove methods but I prefer to use `ready()`

**Comment by elyobo** [comment]
Thanks @thgreasi, maybe `.ready()` should be added to [the documentation](localforage.github.io/localForage/)? It does seem like a good idea to cover the case when no storage engines are available at all (e.g. safari in private browsing mode).

Unfortunately it doesn't  prevent the uncaught error that I mentioned from bubbling up.  I [simplified your pen](http://codepen.io/anon/pen/ZLKyqd) so that it only calls `.ready()` and then tries to `.catch()` and log the error, however the `.ready()` is not rejected (the `console.log()` in `.then()` is called instead) and there is still an uncaught error getting logged to the console.  This is in FF private browsing mode.

The same uncaught error can be seen in your original pen, as I showed in the screenshot above.

It looks like the fallback is actually working, as local storage is used instead, however an error from the failed attempt at using indexeddb is not being caught as it should be and so does get exposed.

**Comment by elyobo** [comment]
I really can't see anything wrong with what localforage is doing though, so perhaps this is a FF bug?

Ultimately the failure to connect is calling the [window.onerror](https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror#window.onerror) which we use for logging any uncaught errors in our app; it's generating useless noise for us in this case as the error is expected and _has_ already been handled.

**Comment by thgreasi** [comment]
Adding a `e.preventDefault();` call inside the `indexedDB.open().onerror()` handler seems to prevent the error from reaching `window.onerror()`. [Sample codepen](http://codepen.io/anon/pen/RKVMQp?editors=0010). Any chance this might have other side effects?

**Comment by thgreasi** [comment]
@elyobo thanks for your commitment on this so far.
I just opened PR #648 that possibly resolves this.
As soon as you can confirm that this works for you, we can merge it in for v1.5 .

**Comment by elyobo** [comment]
Thanks @thgreasi that is working for me in your example pen and by testing your branch in my own application.  I had tried `.stopPropagation()` (didn't work) but got dragged away before trying out `.preventDefault()`.  Thank you for investigating and resolving this!

I can't see any other side effects to this.  Also, it sounds like FF's behaviour here is the "right" behavior with regards to propagating the errors to `window.onerror` ([see "Integrate with window.onerror" in the w3c/IndexedDB spec](https://github.com/w3c/IndexedDB/issues/49)) so it does look like this is the right thing to do.

Not directly related, but why does the `.onerror` handler reject with `openreq.error` rather than the error passed in to the handler?

**Comment by thgreasi** [comment]
I'm not sure, aren't they referencing the same object?

**Comment by thgreasi** [comment]
Did you got any weird results on other browsers?

**Comment by elyobo** [comment]
I didn't, but most browsers don't fail there :) I don't have a large suite
available for testing sorry. My colleague reported to me that .ready
resolves rather than rejects in Safari private browsing mode though, even
though there are no valid engines available.

I'm not sure that they're the same object; if multiple errors occur then it
would only be the most recent one, so possibly can't be relied on. Not sure
whether that's possible or not when opening a DB though, I suppose the
first error aborts it and so no more occur. Not on a computer to check
equality right now, but I did have an error calling preventDefault on the
openreq.error object rather than the passed in error, so they may not be
the same in FF (although that does seem weird, so maybe the error was mine).
